### ISSUE TITLE
Credit Batch Balance Doesn't Correspond to Batch-ID and Fails to Send

### ISSUE THREAD

**Issue by S4mmyb** [regen-network/regen-web#1950]
**Describe the bug**
The credit batch balance and credit batch ID do not match in my portfolio, resulting in an inability to send credits through the UI. This happened when I tried to send two consecutive batches to a new address (on mainnet) through the UI. 

Initially I had two batches in my account, both of which I was able to view: 
```
balance:
  address: regen1v2ncquer9r2ytlkxh2djmmsq3e8we6rjc9snfn
  batch_denom: C02-006-20210216-20220215-001
  escrowed_amount: "0"
  retired_amount: "0"
  tradable_amount: "8714"
```
```
balance:
  address: regen1v2ncquer9r2ytlkxh2djmmsq3e8we6rjc9snfn
  batch_denom: C02-005-20191106-20200225-001
  escrowed_amount: "0"
  retired_amount: "0"
  tradable_amount: "1500"
```
I started by sending the second batch, `C02-005-20191106-20200225-001`, from the Evergreen and East project which I was successfully able to transfer ([tx-hash](https://www.mintscan.io/regen/txs/D59F01880D323D7F79F018628B6FD057E650E5F6E7811161D0268709CE2749F3). After refreshing the page, however the Evergreen and East project still displayed in my portfolio, but had the balance of `8714` from the St. Elmo project which had disappeared (see photo below). When I tried to send credits that batch, I am unable to as the UI thinks I'm trying to send from the Evergreen and East project as opposed to the St. Elmo Project (see error below). In the command line I am able to see that my address holds the correct number of credits, but it doesn't match what I see in the UI. 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/regen-network/regen-web/assets/67330492/0e4267ce-97f5-4df0-af4d-f2b3ba205ef0)
![image](https://github.com/regen-network/regen-web/assets/67330492/b91f03bc-27c2-4ecb-b155-93e45ec80c68)
![image](https://github.com/regen-network/regen-web/assets/67330492/4f969a4b-dcdc-458c-ae85-16d8c8414547)
![image](https://github.com/regen-network/regen-web/assets/67330492/2094e7b5-fbe7-49cd-a695-a2ebdd459121)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged
