### ISSUE TITLE
Portfolio doesn't show KSH01 ecocredit balance on mainnet / production

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#2097]
@S4mmyb  and I have successfully issued the first KSH01 credits on mainnet, but the credits aren't showing up in @S4mmyb’s portfolio:
- Portfolio page: https://app.regen.network/profiles/regen1v2ncquer9r2ytlkxh2djmmsq3e8we6rjc9snfn/portfolio
- Query on mainnet shows that this address does indeed hold KSH01 credits: `regen q ecocredit batch-balance KSH01-001-20230101-20230501-001 regen1v2ncquer9r2ytlkxh2djmmsq3e8we6rjc9snfn`

Gives the response below:
```
balance:
  address: regen1v2ncquer9r2ytlkxh2djmmsq3e8we6rjc9snfn
  batch_denom: KSH01-001-20230101-20230501-001
  escrowed_amount: "0"
  retired_amount: "0"
  tradable_amount: "785.7"
```

However, on Redwood we're able to successfully see the credits on his portfolio:
- Portfolio page: https://dev.app.regen.network/profiles/regen1trry4ht2y7z4ee3tnctj7tmk2sceh80l95py2t/portfolio
- Query on redwood: `regen q ecocredit batch-balance KSH01-001-20220101-20230101-005 regen1trry4ht2y7z4ee3tnctj7tmk2sceh80l95py2t`

Gives the response below:
```
balance:
  address: regen1trry4ht2y7z4ee3tnctj7tmk2sceh80l95py2t
  batch_denom: KSH01-001-20220101-20230101-005
  escrowed_amount: "0"
  retired_amount: "0"
  tradable_amount: "1000"
```

Since it only seems to be reproducable on mainnet / prod and not on Redwood, there's a chance that this maybe will be fixed in the release tomorrow?

If not, do y'all have any idea what could be the issue? Things i have thought about:
- pagination of credit batches (but this likely would cause bugs on redwood before causing bugs on mainnet, since redwood has signfiicantly more credit batches)
- Filtering on portfolio pages of only certain credit classes (is there a way that KSH gets filtered out of portfolio pages on mainnet, but not on redwood?)
